/*
 * sensors.h
 *
 *  Created on: May 5, 2025
 *      Author: exysta
 */

#ifndef SMARTWATCHDRIVERS_CUSTOMDRIVERS_SENSORS_H_
#define SMARTWATCHDRIVERS_CUSTOMDRIVERS_SENSORS_H_



#endif /* SMARTWATCHDRIVERS_CUSTOMDRIVERS_SENSORS_H_ */
